import type {
  TopologyBlockSection,
  TopologyDefinition,
  TopologyEdgeRange,
  TopologyEdgeRangeEndpoint,
  TopologySignal,
} from "../lib/topology";

const sectionId = (signalId: string): string => `section-${signalId}`;

const signals: TopologySignal[] = [
  {
    id: "J1",
    edgeId: "bottom-west",
    segmentIndex: 0,
    offset: 728,
    facing: "toward-to",
    mount: "down",
    label: "jalur bawah, arah kanan",
    initialState: false,
    protectedBlockSectionId: sectionId("J1"),
  },
  {
    id: "J2",
    edgeId: "bottom-5-6",
    segmentIndex: 0,
    offset: 230,
    facing: "toward-to",
    mount: "down",
    label: "jalur bawah, kiri P6",
    initialState: false,
    protectedBlockSectionId: sectionId("J2"),
  },
  {
    id: "J3",
    edgeId: "lower-loop",
    segmentIndex: 1,
    offset: 174,
    facing: "toward-to",
    mount: "down",
    label: "lintas simpang bawah, arah kanan",
    initialState: false,
    protectedBlockSectionId: sectionId("J3"),
  },
  {
    id: "J4",
    edgeId: "top-east",
    segmentIndex: 0,
    offset: 116,
    facing: "toward-from",
    mount: "up",
    label: "jalur atas, dua sel kanan P8",
    initialState: false,
    protectedBlockSectionId: sectionId("J4"),
  },
  {
    id: "J5",
    edgeId: "top-3-4",
    segmentIndex: 0,
    offset: 58,
    facing: "toward-from",
    mount: "up",
    label: "jalur atas, kanan P3",
    initialState: false,
    protectedBlockSectionId: sectionId("J5"),
  },
  {
    id: "J6",
    edgeId: "upper-loop",
    segmentIndex: 1,
    offset: 2,
    facing: "toward-from",
    mount: "up",
    label: "lintas simpang atas, arah kiri",
    initialState: false,
    protectedBlockSectionId: sectionId("J6"),
  },
  {
    id: "J7",
    edgeId: "lower-loop",
    segmentIndex: 1,
    offset: 2,
    facing: "toward-from",
    mount: "down",
    label: "lintas simpang bawah, arah kiri",
    initialState: false,
    protectedBlockSectionId: sectionId("J7"),
  },
  {
    id: "B101",
    edgeId: "bottom-west",
    segmentIndex: 0,
    offset: 551,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, J4",
    block: true,
    protectedBlockSectionId: sectionId("B101"),
  },
  {
    id: "B102",
    edgeId: "bottom-west",
    segmentIndex: 0,
    offset: 377,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, G4",
    block: true,
    protectedBlockSectionId: sectionId("B102"),
  },
  {
    id: "B103",
    edgeId: "bottom-west",
    segmentIndex: 0,
    offset: 203,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, D4",
    block: true,
    protectedBlockSectionId: sectionId("B103"),
  },
  {
    id: "B104",
    edgeId: "bottom-west",
    segmentIndex: 0,
    offset: 29,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, A4",
    block: true,
    protectedBlockSectionId: sectionId("B104"),
  },
  {
    id: "A2",
    edgeId: "top-west",
    segmentIndex: 0,
    offset: 6,
    facing: "toward-from",
    mount: "up",
    label: "sinyal masuk, A2 (dikendalikan AI)",
    ai: true,
    protectedBlockSectionId: sectionId("A2"),
  },
  {
    id: "B201",
    edgeId: "top-west",
    segmentIndex: 0,
    offset: 29,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, A2",
    block: true,
    protectedBlockSectionId: sectionId("B201"),
  },
  {
    id: "B202",
    edgeId: "top-west",
    segmentIndex: 0,
    offset: 203,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, D2",
    block: true,
    protectedBlockSectionId: sectionId("B202"),
  },
  {
    id: "B203",
    edgeId: "top-west",
    segmentIndex: 0,
    offset: 377,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, G2",
    block: true,
    protectedBlockSectionId: sectionId("B203"),
  },
  {
    id: "B204",
    edgeId: "top-west",
    segmentIndex: 0,
    offset: 551,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, J2",
    block: true,
    protectedBlockSectionId: sectionId("B204"),
  },
  {
    id: "B9",
    code: "B201",
    edgeId: "top-east",
    segmentIndex: 0,
    offset: 287,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, AC2",
    block: true,
    protectedBlockSectionId: sectionId("B9"),
  },
  {
    id: "B10",
    code: "B202",
    edgeId: "top-east",
    segmentIndex: 0,
    offset: 461,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, AF2",
    block: true,
    protectedBlockSectionId: sectionId("B10"),
  },
  {
    id: "B11",
    code: "B203",
    edgeId: "top-east",
    segmentIndex: 0,
    offset: 635,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, AI2",
    block: true,
    protectedBlockSectionId: sectionId("B11"),
  },
  {
    id: "B12",
    code: "B204",
    edgeId: "top-east",
    segmentIndex: 0,
    offset: 809,
    facing: "toward-from",
    mount: "up",
    label: "sinyal blok, AL2",
    block: true,
    protectedBlockSectionId: sectionId("B12"),
  },
  {
    id: "B109",
    edgeId: "bottom-east",
    segmentIndex: 0,
    offset: 401,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, AC4",
    block: true,
    protectedBlockSectionId: sectionId("B109"),
  },
  {
    id: "B108",
    edgeId: "bottom-east",
    segmentIndex: 0,
    offset: 575,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, AF4",
    block: true,
    protectedBlockSectionId: sectionId("B108"),
  },
  {
    id: "B107",
    edgeId: "bottom-east",
    segmentIndex: 0,
    offset: 749,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, AI4",
    block: true,
    protectedBlockSectionId: sectionId("B107"),
  },
  {
    id: "B106",
    edgeId: "bottom-east",
    segmentIndex: 0,
    offset: 923,
    facing: "toward-to",
    mount: "down",
    label: "sinyal blok, AL4",
    block: true,
    protectedBlockSectionId: sectionId("B106"),
  },
];

const atSignal = (signalId: string): TopologyEdgeRangeEndpoint => ({
  kind: "signal",
  signalId,
});
const atEnd = (end: "from" | "to"): TopologyEdgeRangeEndpoint => ({
  kind: "edge-end",
  end,
});
const range = (
  edgeId: string,
  from: TopologyEdgeRangeEndpoint,
  to: TopologyEdgeRangeEndpoint
): TopologyEdgeRange => ({ edgeId, from, to });
const block = (
  signalId: string,
  edgeRanges: TopologyEdgeRange[],
  legacyOpenEnd?: "west" | "east",
  coverage: TopologyBlockSection["coverage"] = "signal-to-boundary"
): TopologyBlockSection => ({
  id: sectionId(signalId),
  signalId,
  coverage,
  edgeRanges,
  ...(legacyOpenEnd ? { legacyOpenEnd } : {}),
});
const sameEdgeBlock = (
  signalId: string,
  nextSignalId: string,
  edgeId: string
): TopologyBlockSection =>
  block(signalId, [range(edgeId, atSignal(signalId), atSignal(nextSignalId))]);

const blockSections: TopologyBlockSection[] = [
  block("J1", [
    range("bottom-west", atSignal("J1"), atEnd("to")),
    range("bottom-2-5", atEnd("from"), atEnd("to")),
    range("bottom-5-6", atEnd("from"), atSignal("J2")),
  ]),
  block("J2", [
    range("bottom-5-6", atSignal("J2"), atEnd("to")),
    range("bottom-6-7", atEnd("from"), atEnd("to")),
    range("bottom-east", atEnd("from"), atSignal("B109")),
  ]),
  block(
    "J3",
    [range("lower-loop", atEnd("from"), atEnd("to"))],
    "east",
    "whole-track-group"
  ),
  block("J4", [
    range("top-east", atSignal("J4"), atEnd("from")),
    range("top-4-8", atEnd("to"), atEnd("from")),
    range("top-3-4", atEnd("to"), atSignal("J5")),
  ]),
  block("J5", [
    range("top-3-4", atSignal("J5"), atEnd("from")),
    range("top-1-3", atEnd("to"), atEnd("from")),
    range("top-west", atEnd("to"), atSignal("B204")),
  ]),
  block(
    "J6",
    [range("upper-loop", atEnd("to"), atEnd("from"))],
    "west",
    "whole-track-group"
  ),
  block(
    "J7",
    [range("lower-loop", atEnd("to"), atEnd("from"))],
    "west",
    "whole-track-group"
  ),
  sameEdgeBlock("B101", "J1", "bottom-west"),
  sameEdgeBlock("B102", "B101", "bottom-west"),
  sameEdgeBlock("B103", "B102", "bottom-west"),
  sameEdgeBlock("B104", "B103", "bottom-west"),
  block("A2", [range("top-west", atSignal("A2"), atEnd("from"))], "west"),
  sameEdgeBlock("B201", "A2", "top-west"),
  sameEdgeBlock("B202", "B201", "top-west"),
  sameEdgeBlock("B203", "B202", "top-west"),
  sameEdgeBlock("B204", "B203", "top-west"),
  sameEdgeBlock("B9", "J4", "top-east"),
  sameEdgeBlock("B10", "B9", "top-east"),
  sameEdgeBlock("B11", "B10", "top-east"),
  sameEdgeBlock("B12", "B11", "top-east"),
  sameEdgeBlock("B109", "B108", "bottom-east"),
  sameEdgeBlock("B108", "B107", "bottom-east"),
  sameEdgeBlock("B107", "B106", "bottom-east"),
  block(
    "B106",
    [range("bottom-east", atSignal("B106"), atEnd("to"))],
    "east"
  ),
];

export const BEKASI_TAMBUN_CIBITUNG_TOPOLOGY: TopologyDefinition = {
  nodes: [
    { id: "tlL", point: [-406, 89], kind: "boundary" },
    { id: "p1", point: [326, 89], kind: "switch" },
    { id: "p3", point: [500, 89], kind: "switch" },
    { id: "p4", point: [786, 89], kind: "switch" },
    { id: "p8", point: [960, 89], kind: "switch" },
    { id: "tlR", point: [1798, 89], kind: "boundary" },
    { id: "blL", point: [-406, 205], kind: "boundary" },
    { id: "p2", point: [438, 205], kind: "switch" },
    { id: "p5", point: [500, 205], kind: "switch" },
    { id: "p6", point: [788, 205], kind: "switch" },
    { id: "p7", point: [846, 205], kind: "switch" },
    { id: "blR", point: [1798, 205], kind: "boundary" },
  ],
  edges: [
    {
      id: "top-west",
      from: "tlL",
      to: "p1",
      geometry: [{ point: [-406, 89] }, { point: [326, 89] }],
      role: "main",
      trackGroupId: "top-main",
      normalDirection: "left",
      renderBreakpoints: [[64, 89]],
      renderSlots: [0, 4],
    },
    {
      id: "top-1-3",
      from: "p1",
      to: "p3",
      geometry: [{ point: [326, 89] }, { point: [500, 89] }],
      role: "main",
      trackGroupId: "top-main",
      normalDirection: "left",
      renderSlots: [5],
    },
    {
      id: "top-3-4",
      from: "p3",
      to: "p4",
      geometry: [{ point: [500, 89] }, { point: [786, 89] }],
      role: "main",
      trackGroupId: "top-main",
      normalDirection: "left",
      renderSlots: [6],
    },
    {
      id: "top-4-8",
      from: "p4",
      to: "p8",
      geometry: [{ point: [786, 89] }, { point: [960, 89] }],
      role: "main",
      trackGroupId: "top-main",
      normalDirection: "left",
      renderSlots: [7],
    },
    {
      id: "top-east",
      from: "p8",
      to: "tlR",
      geometry: [{ point: [960, 89] }, { point: [1798, 89] }],
      role: "main",
      trackGroupId: "top-main",
      normalDirection: "left",
      renderBreakpoints: [[1162, 89]],
      renderSlots: [8, 1],
    },
    {
      id: "bottom-west",
      from: "blL",
      to: "p2",
      geometry: [{ point: [-406, 205] }, { point: [438, 205] }],
      role: "main",
      trackGroupId: "bottom-main",
      normalDirection: "right",
      renderBreakpoints: [[62, 205]],
      renderSlots: [2, 9],
    },
    {
      id: "bottom-2-5",
      from: "p2",
      to: "p5",
      geometry: [{ point: [438, 205] }, { point: [500, 205] }],
      role: "main",
      trackGroupId: "bottom-main",
      normalDirection: "right",
      renderSlots: [10],
    },
    {
      id: "bottom-5-6",
      from: "p5",
      to: "p6",
      geometry: [{ point: [500, 205] }, { point: [788, 205] }],
      role: "main",
      trackGroupId: "bottom-main",
      normalDirection: "right",
      renderSlots: [11],
    },
    {
      id: "bottom-6-7",
      from: "p6",
      to: "p7",
      geometry: [{ point: [788, 205] }, { point: [846, 205] }],
      role: "main",
      trackGroupId: "bottom-main",
      normalDirection: "right",
      renderSlots: [12],
    },
    {
      id: "bottom-east",
      from: "p7",
      to: "blR",
      geometry: [{ point: [846, 205] }, { point: [1798, 205] }],
      role: "main",
      trackGroupId: "bottom-main",
      normalDirection: "right",
      renderBreakpoints: [[1162, 205]],
      renderSlots: [13, 3],
    },
    {
      id: "crossover-west",
      from: "p1",
      to: "p2",
      geometry: [{ point: [326, 89] }, { point: [438, 205] }],
      role: "crossover",
      trackGroupId: "crossover-west-group",
      renderSlots: [14],
      renderEndpointOverride: {
        from: [326, 90],
        reason: "Preserve the legacy rendered P1 endpoint without changing its logical coordinate",
      },
    },
    {
      id: "upper-loop",
      from: "p3",
      to: "p4",
      geometry: [
        { point: [500, 89] },
        { point: [556, 148], compatibilityNodeId: "ul1" },
        { point: [730, 148], compatibilityNodeId: "ul2" },
        { point: [786, 89] },
      ],
      role: "loop",
      trackGroupId: "upper-loop-group",
      normalDirection: "left",
      renderSlots: [16, 17, 18],
    },
    {
      id: "lower-loop",
      from: "p5",
      to: "p6",
      geometry: [
        { point: [500, 205] },
        { point: [556, 264], compatibilityNodeId: "ll1" },
        { point: [730, 264], compatibilityNodeId: "ll2" },
        { point: [788, 205] },
      ],
      role: "loop",
      trackGroupId: "lower-loop-group",
      normalDirection: "right",
      renderSlots: [19, 20, 21],
    },
    {
      id: "crossover-east",
      from: "p7",
      to: "p8",
      geometry: [{ point: [846, 205] }, { point: [960, 89] }],
      role: "crossover",
      trackGroupId: "crossover-east-group",
      renderSlots: [15],
    },
  ],
  switches: [
    {
      id: 1,
      nodeId: "p1",
      common: { edgeId: "top-west", end: "to" },
      normal: { edgeId: "top-1-3", end: "from" },
      reversed: { edgeId: "crossover-west", end: "from" },
      initialState: "normal",
      controlGroupId: "crossing-west",
      dashSide: "right",
      label: "persilangan kiri, ujung atas",
    },
    {
      id: 2,
      nodeId: "p2",
      common: { edgeId: "bottom-2-5", end: "from" },
      normal: { edgeId: "bottom-west", end: "to" },
      reversed: { edgeId: "crossover-west", end: "to" },
      initialState: "normal",
      controlGroupId: "crossing-west",
      dashSide: "left",
      label: "persilangan kiri, ujung bawah",
    },
    {
      id: 3,
      nodeId: "p3",
      common: { edgeId: "top-1-3", end: "to" },
      normal: { edgeId: "top-3-4", end: "from" },
      reversed: { edgeId: "upper-loop", end: "from" },
      initialState: "normal",
      controlGroupId: "point-3",
      dashSide: "right",
      label: "lintas simpang atas, ujung barat",
    },
    {
      id: 4,
      nodeId: "p4",
      common: { edgeId: "top-4-8", end: "from" },
      normal: { edgeId: "top-3-4", end: "to" },
      reversed: { edgeId: "upper-loop", end: "to" },
      initialState: "normal",
      controlGroupId: "point-4",
      dashSide: "left",
      label: "lintas simpang atas, ujung timur",
    },
    {
      id: 5,
      nodeId: "p5",
      common: { edgeId: "bottom-2-5", end: "to" },
      normal: { edgeId: "bottom-5-6", end: "from" },
      reversed: { edgeId: "lower-loop", end: "from" },
      initialState: "normal",
      controlGroupId: "point-5",
      dashSide: "right",
      label: "lintas simpang bawah, ujung barat",
    },
    {
      id: 6,
      nodeId: "p6",
      common: { edgeId: "bottom-6-7", end: "from" },
      normal: { edgeId: "bottom-5-6", end: "to" },
      reversed: { edgeId: "lower-loop", end: "to" },
      initialState: "normal",
      controlGroupId: "point-6",
      dashSide: "left",
      label: "lintas simpang bawah, ujung timur",
    },
    {
      id: 7,
      nodeId: "p7",
      common: { edgeId: "bottom-6-7", end: "to" },
      normal: { edgeId: "bottom-east", end: "from" },
      reversed: { edgeId: "crossover-east", end: "from" },
      initialState: "normal",
      controlGroupId: "crossing-east",
      dashSide: "right",
      label: "persilangan kanan, ujung bawah",
    },
    {
      id: 8,
      nodeId: "p8",
      common: { edgeId: "top-east", end: "from" },
      normal: { edgeId: "top-4-8", end: "to" },
      reversed: { edgeId: "crossover-east", end: "to" },
      initialState: "normal",
      controlGroupId: "crossing-east",
      dashSide: "left",
      label: "persilangan kanan, ujung atas",
    },
  ],
  controlGroups: [
    { id: "crossing-west", switchIds: [1, 2], coupled: true },
    { id: "point-3", switchIds: [3], coupled: false },
    { id: "point-4", switchIds: [4], coupled: false },
    { id: "point-5", switchIds: [5], coupled: false },
    { id: "point-6", switchIds: [6], coupled: false },
    { id: "crossing-east", switchIds: [7, 8], coupled: true },
  ],
  signals,
  trackGroups: [
    {
      id: "top-main",
      role: "main",
      edgeIds: ["top-west", "top-1-3", "top-3-4", "top-4-8", "top-east"],
      normalDirection: "left",
    },
    {
      id: "bottom-main",
      role: "main",
      edgeIds: [
        "bottom-west",
        "bottom-2-5",
        "bottom-5-6",
        "bottom-6-7",
        "bottom-east",
      ],
      normalDirection: "right",
    },
    {
      id: "upper-loop-group",
      role: "loop",
      edgeIds: ["upper-loop"],
      normalDirection: "left",
    },
    {
      id: "lower-loop-group",
      role: "loop",
      edgeIds: ["lower-loop"],
      normalDirection: "right",
    },
    {
      id: "crossover-west-group",
      role: "crossover",
      edgeIds: ["crossover-west"],
    },
    {
      id: "crossover-east-group",
      role: "crossover",
      edgeIds: ["crossover-east"],
    },
  ],
  blockSections,
  stationStopPoints: [
    { stationCode: "BKST", edgeId: "top-west", segmentIndex: 0, offset: 116 },
    { stationCode: "BKST", edgeId: "bottom-west", segmentIndex: 0, offset: 116 },
    { stationCode: "TB", edgeId: "top-3-4", segmentIndex: 0, offset: 138 },
    { stationCode: "TB", edgeId: "upper-loop", segmentIndex: 1, offset: 82 },
    { stationCode: "TB", edgeId: "bottom-5-6", segmentIndex: 0, offset: 138 },
    { stationCode: "TB", edgeId: "lower-loop", segmentIndex: 1, offset: 82 },
    { stationCode: "CIT", edgeId: "top-east", segmentIndex: 0, offset: 722 },
    { stationCode: "CIT", edgeId: "bottom-east", segmentIndex: 0, offset: 836 },
  ],
  legacyNodeOrder: [
    "tlL",
    "p1",
    "p3",
    "ul1",
    "ul2",
    "p4",
    "p8",
    "tlR",
    "blL",
    "p2",
    "p5",
    "ll1",
    "ll2",
    "p6",
    "p7",
    "blR",
  ],
};
